//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schematask
{
    using System;
    using System.Collections.Generic;
    
    public partial class arrangement
    {
        public System.DateTime day { get; set; }
        public int student_sid { get; set; }
        public int course_courseid { get; set; }
        public int invigilator_invigilatorid { get; set; }
        public int examcenter_centerid { get; set; }
        public int room_roomid { get; set; }
        public int school_schoolid { get; set; }
    
        public virtual student student { get; set; }
        public virtual course course { get; set; }
        public virtual invigilator invigilator { get; set; }
        public virtual examcenter examcenter { get; set; }
        public virtual room room { get; set; }
        public virtual school school { get; set; }
    }
}
